CREATE TABLE TEMPERATURA (
IDTEMPERATURA SERIAL PRIMARY KEY,
TERMOMETRO_INTERNO CHAR(8),
HORA_TEMP TIME,
TERMOMETRO_EXTERNO CHAR(8)
);

CREATE TABLE ORGAO (
HORA_CAPTACAO TIME,
ORGAO VARCHAR(15),
IDORGAO SERIAL PRIMARY KEY,
TEMPO_VIDA TIME,
IDTRANSPLANTE SERIAL
);

CREATE TABLE TRANSPLANTE (
DATA_TRANSPLANTE DATE,
IDTRANSPLANTE SERIAL PRIMARY KEY
);

CREATE TABLE DOADOR (
TIPO_SANGUINEO CHAR(3),
HORA_OBITO TIME,
IDPESSOA SERIAL
);

CREATE TABLE CAIXA (
CAPACIDADE INTEGER,
IDENTIFICACAO VARCHAR(30),
IDCAIXA SERIAL PRIMARY KEY,
VALIDADE DATE
);

CREATE TABLE APARELHO (
MODELO VARCHAR(30),
VALIDADE DATE,
IDAPARELHO SERIAL PRIMARY KEY,
SERIE VARCHAR(10)
);

CREATE TABLE LOCALIZACAO (
LONGITUDE VARCHAR(10),
HORA_LOC TIME,
IDLOCALIZACAO SERIAL PRIMARY KEY,
LATITUDE VARCHAR(10)
);

CREATE TABLE TRANSPORTE (
TEMP_FINAL CHAR(5),
DATA DATE,
LATITUDE_INICIAL VARCHAR(10),
LONGITUDE_INICIAL VARCHAR(10),
IDTRANSPORTE SERIAL PRIMARY KEY,
HORA_SAIDA TIME,
TEMP_INICIAL CHAR(5),
DESTINO VARCHAR(150),
ORIGEM VARCHAR(150),
LONGITUDE_FINAL VARCHAR(10),
LATITUDE_FINAL VARCHAR(10),
IDORGAO SERIAL,
IDTEMPERATURA SERIAL,
IDAPARELHO SERIAL,
IDCAIXA SERIAL,
IDLOCALIZACAO SERIAL,
FOREIGN KEY(IDORGAO) REFERENCES ORGAO (IDORGAO),
FOREIGN KEY(IDTEMPERATURA) REFERENCES TEMPERATURA (IDTEMPERATURA),
FOREIGN KEY(IDAPARELHO) REFERENCES APARELHO (IDAPARELHO),
FOREIGN KEY(IDCAIXA) REFERENCES CAIXA (IDCAIXA),
FOREIGN KEY(IDLOCALIZACAO) REFERENCES LOCALIZACAO (IDLOCALIZACAO)
);

CREATE TABLE MOTORISTA (
CNH VARCHAR(11),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(100),
VALIDADE_CNH DATE,
IDPESSOA SERIAL
);

CREATE TABLE RESPONSAVEL (
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
IDPESSOA SERIAL
);

CREATE TABLE RECEPTOR (
TIPO_SANGUINEO CHAR(3),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(10),
IDPESSOA SERIAL
);

CREATE TABLE USUARIO (
TELEFONE VARCHAR(15),
EMAIL VARCHAR(100),
LOGIN VARCHAR(10),
SENHA VARCHAR(10),
IDPESSOA SERIAL
);

CREATE TABLE PESSOA (
NOME VARCHAR(150),
CIDADE VARCHAR(50),
NASCIMENTO DATE,
UF CHAR(2),
CEP VARCHAR(9),
RG CHAR(9),
CPF VARCHAR(14),
ENDERECO VARCHAR(150),
BAIRRO VARCHAR(150),
IDPESSOA SERIAL PRIMARY KEY
);

ALTER TABLE ORGAO ADD FOREIGN KEY(IDTRANSPLANTE) REFERENCES TRANSPLANTE (IDTRANSPLANTE);
ALTER TABLE DOADOR ADD FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE MOTORISTA ADD FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE RESPONSAVEL ADD FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE RECEPTOR ADD FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE USUARIO ADD FOREIGN KEY(IDPESSOA) REFERENCES PESSOA (IDPESSOA);


