

CREATE TABLE CAIXA (
IDCAIXA SERIAL PRIMARY KEY,
VALIDADE DATE,
IDENTIFICACAO VARCHAR(30),
CAPACIDADE INTEGER,
IDAPARELHO SERIAL,
IDMOTORISTA SERIAL,
IDORGAO SERIAL
);

CREATE TABLE APARELHO (
IDAPARELHO SERIAL PRIMARY KEY,
SERIE VARCHAR(10),
VALIDADE DATE,
MODELO VARCHAR(30)
);

CREATE TABLE ORGAO (
IDORGAO SERIAL PRIMARY KEY,
HORA_CAPTACAO TIME,
ORGAO VARCHAR(15),
TEMPO_VIDA TIME,
IDUSUARIO SERIAL,
IDTRANSPLANTE VARCHAR(10),
IDDOADOR SERIAL
);

CREATE TABLE DOADOR (
IDDOADOR SERIAL PRIMARY KEY,
NOME VARCHAR(100),
CPF VARCHAR(14),
UF CHAR(2),
ENDERECO VARCHAR(150),
TIPO_SANGUINEO CHAR(3),
CIDADE VARCHAR(50),
BAIRRO VARCHAR(100),
CEP CHAR(9),
RG CHAR(9),
HORA_OBITO TIME,
NASCIMENTO DATE,
IDPARENTE SERIAL,
IDUSUARIO SERIAL
);

CREATE TABLE TRANSPORTE (
IDTRANSPORTE VARCHAR(10) PRIMARY KEY,
TEMP_FINAL CHAR(5),
TEMP_INICIAL CHAR(5),
HORA_SAIDA TIME,
ORIGEM VARCHAR(150),
DATA DATE,
LATITUDE_INICIAL VARCHAR(10),
LATITUDE_FINAL VARCHAR(10),
LONGITUDE_INICIAL VARCHAR(10),
DESTINO VARCHAR(150),
LONGITUDE_FINAL VARCHAR(10),
IDCAIXA SERIAL,
IDAPARELHO SERIAL,
IDMOTORISTA SERIAL,
FOREIGN KEY(IDCAIXA) REFERENCES CAIXA (IDCAIXA),
FOREIGN KEY(IDAPARELHO) REFERENCES APARELHO (IDAPARELHO)
);

CREATE TABLE TRANSPLANTE (
IDTRANSPLANTE VARCHAR(10) PRIMARY KEY,
IDRECEPTOR SERIAL,
IDUSUARIO SERIAL,
DATA_TRANSPLANTE DATE
);

CREATE TABLE TEMPERATURA (
IDTEMPERATURA VARCHAR(10) PRIMARY KEY,
TERMOMETRO_EXTERNO CHAR(8),
TERMOMETRO_INTERNO CHAR(8),
HORA_TEMP TIME,
IDAPARELHO SERIAL,
FOREIGN KEY(IDAPARELHO) REFERENCES APARELHO (IDAPARELHO)
);

CREATE TABLE LOCALIZACAO (
IDLOCALIZACAO VARCHAR(10) PRIMARY KEY,
LATITUDE VARCHAR(10),
LONGITUDE VARCHAR(10),
HORA_LOC TIME,
IDAPARELHO SERIAL,
FOREIGN KEY(IDAPARELHO) REFERENCES APARELHO (IDAPARELHO)
);

CREATE TABLE RESPONSAVEL (
IDRESPONSAVEL SERIAL PRIMARY KEY,
NOME VARCHAR(150),
CPF VARCHAR(14),
CEP CHAR(9),
UF CHAR(2),
ENDERECO VARCHAR(150),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(100),
CIDADE VARCHAR(50),
BAIRRO VARCHAR(100),
RG CHAR(9),
NASCIMENTO DATE,
IDUSUARIO SERIAL
);

CREATE TABLE MOTORISTA (
IDMOTORISTA SERIAL PRIMARY KEY,
NOME VARCHAR(150),
CPF VARCHAR(14),
ENDERECO VARCHAR(150),
CEP CHAR(9),
EMAIL VARCHAR(100),
CIDADE VARCHAR(50),
UF CHAR(2),
VALIDADE_CNH DATE,
TELEFONE VARCHAR(15),
CNH VARCHAR(13),
BAIRRO VARCHAR(100),
RG CHAR(9),
NASCIMENTO DATE
);

CREATE TABLE RECEPTOR (
IDRECEPTOR SERIAL PRIMARY KEY,
IDUSUARIO SERIAL,
NOME VARCHAR(150),
CPF VARCHAR(14),
UF CHAR(2),
CIDADE VARCHAR(50),
TIPO_SANGUINEO CHAR(3),
RG CHAR(9),
ENDERECO VARCHAR(150),
CEP CHAR(9),
BAIRRO VARCHAR(100),
NASCIMENTO DATE
);

CREATE TABLE USUARIO (
IDUSUARIO SERIAL PRIMARY KEY,
NOME VARCHAR(150),
CPF VARCHAR(14),
ENDERECO VARCHAR(150),
TELEFONE VARCHAR(15),
SENHA VARCHAR(10),
RG CHAR(9),
CEP VARCHAR(9),
UF CHAR(2),
CIDADE VARCHAR(50),
LOGIN VARCHAR(15),
EMAIL VARCHAR(100),
NASCIMENTO DATE,
BAIRRO VARCHAR(10)
);

ALTER TABLE CAIXA ADD FOREIGN KEY(IDAPARELHO) REFERENCES APARELHO (IDAPARELHO);
ALTER TABLE CAIXA ADD FOREIGN KEY(IDMOTORISTA) REFERENCES MOTORISTA (IDMOTORISTA);
ALTER TABLE CAIXA ADD FOREIGN KEY(IDORGAO) REFERENCES ORGAO (IDORGAO);
ALTER TABLE ORGAO ADD FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE ORGAO ADD FOREIGN KEY(IDTRANSPLANTE) REFERENCES TRANSPLANTE (IDTRANSPLANTE);
ALTER TABLE ORGAO ADD FOREIGN KEY(IDDOADOR) REFERENCES DOADOR (IDDOADOR);
ALTER TABLE DOADOR ADD FOREIGN KEY(IDRESPONSAVEL) REFERENCES RESPONSAVEL (IDRESPONSAVEL);
ALTER TABLE DOADOR ADD FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE TRANSPORTE ADD FOREIGN KEY(IDMOTORISTA) REFERENCES MOTORISTA (IDMOTORISTA);
ALTER TABLE TRANSPLANTE ADD FOREIGN KEY(IDRECEPTOR) REFERENCES RECEPTOR (IDRECEPTOR);
ALTER TABLE TRANSPLANTE ADD FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE RESPONSAVEL ADD FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE RECEPTOR ADD FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);