package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aparelho generated by hbm2java
 */
@Entity
@Table(name = "aparelho",
        schema = "public"
)
public class Aparelho implements java.io.Serializable {

    private int idaparelho;
    private String serie;
    private Date validade;
    private String modelo;
    private Set<Caixa> caixas = new HashSet<Caixa>(0);
    private Set<Localizacao> localizacaos = new HashSet<Localizacao>(0);
    private Set<Temperatura> temperaturas = new HashSet<Temperatura>(0);
    private Set<Transporte> transportes = new HashSet<Transporte>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idaparelho", nullable = false)
    public int getIdaparelho() {
        return this.idaparelho;
    }

    public void setIdaparelho(int idaparelho) {
        this.idaparelho = idaparelho;
    }

    @Column(name = "serie", length = 10)
    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "validade", length = 13)
    public Date getValidade() {
        return this.validade;
    }

    public void setValidade(Date validade) {
        this.validade = validade;
    }

    @Column(name = "modelo", length = 30)
    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aparelho")
    public Set<Caixa> getCaixas() {
        return this.caixas;
    }

    public void setCaixas(Set<Caixa> caixas) {
        this.caixas = caixas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aparelho")
    public Set<Localizacao> getLocalizacaos() {
        return this.localizacaos;
    }

    public void setLocalizacaos(Set<Localizacao> localizacaos) {
        this.localizacaos = localizacaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aparelho")
    public Set<Temperatura> getTemperaturas() {
        return this.temperaturas;
    }

    public void setTemperaturas(Set<Temperatura> temperaturas) {
        this.temperaturas = temperaturas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aparelho")
    public Set<Transporte> getTransportes() {
        return this.transportes;
    }

    public void setTransportes(Set<Transporte> transportes) {
        this.transportes = transportes;
    }

}
