package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private int idcaixa;
     private Aparelho aparelho;
     private Motorista motorista;
     private Orgao orgao;
     private Date validade;
     private String identificacao;
     private Integer capacidade;
     private Set transportes = new HashSet(0);

    public Caixa() {
    }

	
    public Caixa(int idcaixa, Aparelho aparelho, Motorista motorista, Orgao orgao) {
        this.idcaixa = idcaixa;
        this.aparelho = aparelho;
        this.motorista = motorista;
        this.orgao = orgao;
    }
    public Caixa(int idcaixa, Aparelho aparelho, Motorista motorista, Orgao orgao, Date validade, String identificacao, Integer capacidade, Set transportes) {
       this.idcaixa = idcaixa;
       this.aparelho = aparelho;
       this.motorista = motorista;
       this.orgao = orgao;
       this.validade = validade;
       this.identificacao = identificacao;
       this.capacidade = capacidade;
       this.transportes = transportes;
    }
   
    public int getIdcaixa() {
        return this.idcaixa;
    }
    
    public void setIdcaixa(int idcaixa) {
        this.idcaixa = idcaixa;
    }
    public Aparelho getAparelho() {
        return this.aparelho;
    }
    
    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }
    public Motorista getMotorista() {
        return this.motorista;
    }
    
    public void setMotorista(Motorista motorista) {
        this.motorista = motorista;
    }
    public Orgao getOrgao() {
        return this.orgao;
    }
    
    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
    }
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }
    public String getIdentificacao() {
        return this.identificacao;
    }
    
    public void setIdentificacao(String identificacao) {
        this.identificacao = identificacao;
    }
    public Integer getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(Integer capacidade) {
        this.capacidade = capacidade;
    }
    public Set getTransportes() {
        return this.transportes;
    }
    
    public void setTransportes(Set transportes) {
        this.transportes = transportes;
    }




}


