package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caixa generated by hbm2java
 */
@Entity
@Table(name = "caixa",
         schema = "public"
)
public class Caixa implements java.io.Serializable {

    private int idcaixa;
    private Aparelho aparelho;
    private Motorista motorista;
    private Orgao orgao;
    private Date validade;
    private String identificacao;
    private Integer capacidade;
    private Set<Transporte> transportes = new HashSet<Transporte>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idcaixa", nullable = false)
    public int getIdcaixa() {
        return this.idcaixa;
    }

    public void setIdcaixa(int idcaixa) {
        this.idcaixa = idcaixa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idaparelho", nullable = false)
    public Aparelho getAparelho() {
        return this.aparelho;
    }

    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idmotorista", nullable = false)
    public Motorista getMotorista() {
        return this.motorista;
    }

    public void setMotorista(Motorista motorista) {
        this.motorista = motorista;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idorgao", nullable = false)
    public Orgao getOrgao() {
        return this.orgao;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "validade", length = 13)
    public Date getValidade() {
        return this.validade;
    }

    public void setValidade(Date validade) {
        this.validade = validade;
    }

    @Column(name = "identificacao", length = 30)
    public String getIdentificacao() {
        return this.identificacao;
    }

    public void setIdentificacao(String identificacao) {
        this.identificacao = identificacao;
    }

    @Column(name = "capacidade")
    public Integer getCapacidade() {
        return this.capacidade;
    }

    public void setCapacidade(Integer capacidade) {
        this.capacidade = capacidade;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caixa")
    public Set<Transporte> getTransportes() {
        return this.transportes;
    }

    public void setTransportes(Set<Transporte> transportes) {
        this.transportes = transportes;
    }

}
