package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doador generated by hbm2java
 */
@Entity
@Table(name = "doador",
         schema = "public"
)
public class Doador implements java.io.Serializable {

    private int iddoador;
    private Responsavel responsavel;
    private Usuario usuario;
    private String nome;
    private String cpf;
    private String uf;
    private String endereco;
    private String tipoSanguineo;
    private String cidade;
    private String bairro;
    private String cep;
    private String rg;
    private Date horaObito;
    private Date nascimento;
    private String orgaoDoado;
    private Set<Orgao> orgaos = new HashSet<Orgao>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "iddoador", nullable = false)
    public int getIddoador() {
        return this.iddoador;
    }

    public void setIddoador(int iddoador) {
        this.iddoador = iddoador;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idresponsavel", nullable = false)
    public Responsavel getResponsavel() {
        return this.responsavel;
    }

    public void setResponsavel(Responsavel responsavel) {
        this.responsavel = responsavel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idusuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "nome", length = 100)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "cpf", length = 14)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "uf", length = 2)
    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    @Column(name = "endereco", length = 150)
    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Column(name = "tipo_sanguineo", length = 3)
    public String getTipoSanguineo() {
        return this.tipoSanguineo;
    }

    public void setTipoSanguineo(String tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    @Column(name = "cidade", length = 50)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "bairro", length = 100)
    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @Column(name = "cep", length = 9)
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Column(name = "rg", length = 9)
    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_obito", length = 15)
    public Date getHoraObito() {
        return this.horaObito;
    }

    public void setHoraObito(Date horaObito) {
        this.horaObito = horaObito;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "nascimento", length = 13)
    public Date getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }

    @Column(name = "orgao_doado", length = 10)
    public String getOrgaoDoado() {
        return this.orgaoDoado;
    }

    public void setOrgaoDoado(String orgaoDoado) {
        this.orgaoDoado = orgaoDoado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "doador")
    public Set<Orgao> getOrgaos() {
        return this.orgaos;
    }

    public void setOrgaos(Set<Orgao> orgaos) {
        this.orgaos = orgaos;
    }

}
