package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Localizacao generated by hbm2java
 */
public class Localizacao  implements java.io.Serializable {


     private String idlocalizacao;
     private Aparelho aparelho;
     private String latitude;
     private String longitude;
     private Date horaLoc;

    public Localizacao() {
    }

	
    public Localizacao(String idlocalizacao, Aparelho aparelho) {
        this.idlocalizacao = idlocalizacao;
        this.aparelho = aparelho;
    }
    public Localizacao(String idlocalizacao, Aparelho aparelho, String latitude, String longitude, Date horaLoc) {
       this.idlocalizacao = idlocalizacao;
       this.aparelho = aparelho;
       this.latitude = latitude;
       this.longitude = longitude;
       this.horaLoc = horaLoc;
    }
   
    public String getIdlocalizacao() {
        return this.idlocalizacao;
    }
    
    public void setIdlocalizacao(String idlocalizacao) {
        this.idlocalizacao = idlocalizacao;
    }
    public Aparelho getAparelho() {
        return this.aparelho;
    }
    
    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public Date getHoraLoc() {
        return this.horaLoc;
    }
    
    public void setHoraLoc(Date horaLoc) {
        this.horaLoc = horaLoc;
    }




}


