package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Motorista generated by hbm2java
 */
public class Motorista  implements java.io.Serializable {


     private int idmotorista;
     private String nome;
     private String cpf;
     private String endereco;
     private String cep;
     private String email;
     private String cidade;
     private String uf;
     private Date validadeCnh;
     private String telefone;
     private String cnh;
     private String bairro;
     private String rg;
     private Date nascimento;
     private Set caixas = new HashSet(0);
     private Set transportes = new HashSet(0);

    public Motorista() {
    }

	
    public Motorista(int idmotorista) {
        this.idmotorista = idmotorista;
    }
    public Motorista(int idmotorista, String nome, String cpf, String endereco, String cep, String email, String cidade, String uf, Date validadeCnh, String telefone, String cnh, String bairro, String rg, Date nascimento, Set caixas, Set transportes) {
       this.idmotorista = idmotorista;
       this.nome = nome;
       this.cpf = cpf;
       this.endereco = endereco;
       this.cep = cep;
       this.email = email;
       this.cidade = cidade;
       this.uf = uf;
       this.validadeCnh = validadeCnh;
       this.telefone = telefone;
       this.cnh = cnh;
       this.bairro = bairro;
       this.rg = rg;
       this.nascimento = nascimento;
       this.caixas = caixas;
       this.transportes = transportes;
    }
   
    public int getIdmotorista() {
        return this.idmotorista;
    }
    
    public void setIdmotorista(int idmotorista) {
        this.idmotorista = idmotorista;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public Date getValidadeCnh() {
        return this.validadeCnh;
    }
    
    public void setValidadeCnh(Date validadeCnh) {
        this.validadeCnh = validadeCnh;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCnh() {
        return this.cnh;
    }
    
    public void setCnh(String cnh) {
        this.cnh = cnh;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }
    public Set getTransportes() {
        return this.transportes;
    }
    
    public void setTransportes(Set transportes) {
        this.transportes = transportes;
    }




}


