package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Motorista generated by hbm2java
 */
@Entity
@Table(name = "motorista",
        schema = "public"
)
public class Motorista implements java.io.Serializable {

    private int idmotorista;
    private String nome;
    private String cpf;
    private String endereco;
    private String cep;
    private String email;
    private String cidade;
    private String uf;
    private Date validadeCnh;
    private String telefone;
    private String cnh;
    private String bairro;
    private String rg;
    private Date nascimento;
    private Set<Caixa> caixas = new HashSet<Caixa>(0);
    private Set<Transporte> transportes = new HashSet<Transporte>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idmotorista", nullable = false)
    public int getIdmotorista() {
        return this.idmotorista;
    }

    public void setIdmotorista(int idmotorista) {
        this.idmotorista = idmotorista;
    }

    @Column(name = "nome", length = 150)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "cpf", length = 14)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "endereco", length = 150)
    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Column(name = "cep", length = 9)
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Column(name = "email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "cidade", length = 50)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "uf", length = 2)
    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "validade_cnh", length = 13)
    public Date getValidadeCnh() {
        return this.validadeCnh;
    }

    public void setValidadeCnh(Date validadeCnh) {
        this.validadeCnh = validadeCnh;
    }

    @Column(name = "telefone", length = 15)
    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    @Column(name = "cnh", length = 13)
    public String getCnh() {
        return this.cnh;
    }

    public void setCnh(String cnh) {
        this.cnh = cnh;
    }

    @Column(name = "bairro", length = 100)
    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @Column(name = "rg", length = 9)
    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "nascimento", length = 13)
    public Date getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "motorista")
    public Set<Caixa> getCaixas() {
        return this.caixas;
    }

    public void setCaixas(Set<Caixa> caixas) {
        this.caixas = caixas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "motorista")
    public Set<Transporte> getTransportes() {
        return this.transportes;
    }

    public void setTransportes(Set<Transporte> transportes) {
        this.transportes = transportes;
    }

}
