package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orgao generated by hbm2java
 */
public class Orgao  implements java.io.Serializable {


     private int idorgao;
     private Doador doador;
     private Transplante transplante;
     private Usuario usuario;
     private Date horaCaptacao;
     private String orgao;
     private Date tempoVida;
     private Set caixas = new HashSet(0);

    public Orgao() {
    }

	
    public Orgao(int idorgao, Doador doador, Usuario usuario) {
        this.idorgao = idorgao;
        this.doador = doador;
        this.usuario = usuario;
    }
    public Orgao(int idorgao, Doador doador, Transplante transplante, Usuario usuario, Date horaCaptacao, String orgao, Date tempoVida, Set caixas) {
       this.idorgao = idorgao;
       this.doador = doador;
       this.transplante = transplante;
       this.usuario = usuario;
       this.horaCaptacao = horaCaptacao;
       this.orgao = orgao;
       this.tempoVida = tempoVida;
       this.caixas = caixas;
    }
   
    public int getIdorgao() {
        return this.idorgao;
    }
    
    public void setIdorgao(int idorgao) {
        this.idorgao = idorgao;
    }
    public Doador getDoador() {
        return this.doador;
    }
    
    public void setDoador(Doador doador) {
        this.doador = doador;
    }
    public Transplante getTransplante() {
        return this.transplante;
    }
    
    public void setTransplante(Transplante transplante) {
        this.transplante = transplante;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraCaptacao() {
        return this.horaCaptacao;
    }
    
    public void setHoraCaptacao(Date horaCaptacao) {
        this.horaCaptacao = horaCaptacao;
    }
    public String getOrgao() {
        return this.orgao;
    }
    
    public void setOrgao(String orgao) {
        this.orgao = orgao;
    }
    public Date getTempoVida() {
        return this.tempoVida;
    }
    
    public void setTempoVida(Date tempoVida) {
        this.tempoVida = tempoVida;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }




}


