package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receptor generated by hbm2java
 */
public class Receptor  implements java.io.Serializable {


     private int idreceptor;
     private Usuario usuario;
     private String nome;
     private String cpf;
     private String uf;
     private String cidade;
     private String tipoSanguineo;
     private String rg;
     private String endereco;
     private String cep;
     private String bairro;
     private Date nascimento;
     private Set transplantes = new HashSet(0);

    public Receptor() {
    }

	
    public Receptor(int idreceptor, Usuario usuario) {
        this.idreceptor = idreceptor;
        this.usuario = usuario;
    }
    public Receptor(int idreceptor, Usuario usuario, String nome, String cpf, String uf, String cidade, String tipoSanguineo, String rg, String endereco, String cep, String bairro, Date nascimento, Set transplantes) {
       this.idreceptor = idreceptor;
       this.usuario = usuario;
       this.nome = nome;
       this.cpf = cpf;
       this.uf = uf;
       this.cidade = cidade;
       this.tipoSanguineo = tipoSanguineo;
       this.rg = rg;
       this.endereco = endereco;
       this.cep = cep;
       this.bairro = bairro;
       this.nascimento = nascimento;
       this.transplantes = transplantes;
    }
   
    public int getIdreceptor() {
        return this.idreceptor;
    }
    
    public void setIdreceptor(int idreceptor) {
        this.idreceptor = idreceptor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getTipoSanguineo() {
        return this.tipoSanguineo;
    }
    
    public void setTipoSanguineo(String tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public Set getTransplantes() {
        return this.transplantes;
    }
    
    public void setTransplantes(Set transplantes) {
        this.transplantes = transplantes;
    }




}


