package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receptor generated by hbm2java
 */
@Entity
@Table(name = "receptor",
         schema = "public"
)
public class Receptor implements java.io.Serializable {

    private int idreceptor;
    private Usuario usuario;
    private String nome;
    private String cpf;
    private String uf;
    private String cidade;
    private String tipoSanguineo;
    private String rg;
    private String endereco;
    private String cep;
    private String bairro;
    private Date nascimento;
    private Set<Transplante> transplantes = new HashSet<Transplante>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idreceptor", nullable = false)
    public int getIdreceptor() {
        return this.idreceptor;
    }

    public void setIdreceptor(int idreceptor) {
        this.idreceptor = idreceptor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idusuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "nome", length = 150)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "cpf", length = 14)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "uf", length = 2)
    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    @Column(name = "cidade", length = 50)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "tipo_sanguineo", length = 3)
    public String getTipoSanguineo() {
        return this.tipoSanguineo;
    }

    public void setTipoSanguineo(String tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    @Column(name = "rg", length = 9)
    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    @Column(name = "endereco", length = 150)
    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Column(name = "cep", length = 9)
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Column(name = "bairro", length = 100)
    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "nascimento", length = 13)
    public Date getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "receptor")
    public Set<Transplante> getTransplantes() {
        return this.transplantes;
    }

    public void setTransplantes(Set<Transplante> transplantes) {
        this.transplantes = transplantes;
    }

}
