package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Responsavel generated by hbm2java
 */
public class Responsavel  implements java.io.Serializable {


     private int idresponsavel;
     private Usuario usuario;
     private String nome;
     private String cpf;
     private String cep;
     private String uf;
     private String endereco;
     private String telefone;
     private String email;
     private String cidade;
     private String bairro;
     private String rg;
     private Date nascimento;
     private Set doadors = new HashSet(0);

    public Responsavel() {
    }

	
    public Responsavel(int idresponsavel, Usuario usuario) {
        this.idresponsavel = idresponsavel;
        this.usuario = usuario;
    }
    public Responsavel(int idresponsavel, Usuario usuario, String nome, String cpf, String cep, String uf, String endereco, String telefone, String email, String cidade, String bairro, String rg, Date nascimento, Set doadors) {
       this.idresponsavel = idresponsavel;
       this.usuario = usuario;
       this.nome = nome;
       this.cpf = cpf;
       this.cep = cep;
       this.uf = uf;
       this.endereco = endereco;
       this.telefone = telefone;
       this.email = email;
       this.cidade = cidade;
       this.bairro = bairro;
       this.rg = rg;
       this.nascimento = nascimento;
       this.doadors = doadors;
    }
   
    public int getIdresponsavel() {
        return this.idresponsavel;
    }
    
    public void setIdresponsavel(int idresponsavel) {
        this.idresponsavel = idresponsavel;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public Set getDoadors() {
        return this.doadors;
    }
    
    public void setDoadors(Set doadors) {
        this.doadors = doadors;
    }




}


