package Model;
// Generated Oct 13, 2016 9:39:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Temperatura generated by hbm2java
 */
@Entity
@Table(name = "temperatura",
        schema = "public"
)
public class Temperatura implements java.io.Serializable {

    private String idtemperatura;
    private Aparelho aparelho;
    private String termometroExterno;
    private String termometroInterno;
    private Date horaTemp;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idtemperatura", nullable = false, length = 10)
    public String getIdtemperatura() {
        return this.idtemperatura;
    }

    public void setIdtemperatura(String idtemperatura) {
        this.idtemperatura = idtemperatura;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idaparelho", nullable = false)
    public Aparelho getAparelho() {
        return this.aparelho;
    }

    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }

    @Column(name = "termometro_externo", length = 8)
    public String getTermometroExterno() {
        return this.termometroExterno;
    }

    public void setTermometroExterno(String termometroExterno) {
        this.termometroExterno = termometroExterno;
    }

    @Column(name = "termometro_interno", length = 8)
    public String getTermometroInterno() {
        return this.termometroInterno;
    }

    public void setTermometroInterno(String termometroInterno) {
        this.termometroInterno = termometroInterno;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora_temp", length = 15)
    public Date getHoraTemp() {
        return this.horaTemp;
    }

    public void setHoraTemp(Date horaTemp) {
        this.horaTemp = horaTemp;
    }

}
