package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Temperatura generated by hbm2java
 */
public class Temperatura  implements java.io.Serializable {


     private String idtemperatura;
     private Aparelho aparelho;
     private String termometroExterno;
     private String termometroInterno;
     private Date horaTemp;

    public Temperatura() {
    }

	
    public Temperatura(String idtemperatura, Aparelho aparelho) {
        this.idtemperatura = idtemperatura;
        this.aparelho = aparelho;
    }
    public Temperatura(String idtemperatura, Aparelho aparelho, String termometroExterno, String termometroInterno, Date horaTemp) {
       this.idtemperatura = idtemperatura;
       this.aparelho = aparelho;
       this.termometroExterno = termometroExterno;
       this.termometroInterno = termometroInterno;
       this.horaTemp = horaTemp;
    }
   
    public String getIdtemperatura() {
        return this.idtemperatura;
    }
    
    public void setIdtemperatura(String idtemperatura) {
        this.idtemperatura = idtemperatura;
    }
    public Aparelho getAparelho() {
        return this.aparelho;
    }
    
    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }
    public String getTermometroExterno() {
        return this.termometroExterno;
    }
    
    public void setTermometroExterno(String termometroExterno) {
        this.termometroExterno = termometroExterno;
    }
    public String getTermometroInterno() {
        return this.termometroInterno;
    }
    
    public void setTermometroInterno(String termometroInterno) {
        this.termometroInterno = termometroInterno;
    }
    public Date getHoraTemp() {
        return this.horaTemp;
    }
    
    public void setHoraTemp(Date horaTemp) {
        this.horaTemp = horaTemp;
    }




}


