package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transporte generated by hbm2java
 */
public class Transporte  implements java.io.Serializable {


     private String idtransporte;
     private Aparelho aparelho;
     private Caixa caixa;
     private Motorista motorista;
     private String tempFinal;
     private String tempInicial;
     private Date horaSaida;
     private String origem;
     private Date data;
     private String latitudeInicial;
     private String latitudeFinal;
     private String longitudeInicial;
     private String destino;
     private String longitudeFinal;

    public Transporte() {
    }

	
    public Transporte(String idtransporte, Aparelho aparelho, Caixa caixa, Motorista motorista) {
        this.idtransporte = idtransporte;
        this.aparelho = aparelho;
        this.caixa = caixa;
        this.motorista = motorista;
    }
    public Transporte(String idtransporte, Aparelho aparelho, Caixa caixa, Motorista motorista, String tempFinal, String tempInicial, Date horaSaida, String origem, Date data, String latitudeInicial, String latitudeFinal, String longitudeInicial, String destino, String longitudeFinal) {
       this.idtransporte = idtransporte;
       this.aparelho = aparelho;
       this.caixa = caixa;
       this.motorista = motorista;
       this.tempFinal = tempFinal;
       this.tempInicial = tempInicial;
       this.horaSaida = horaSaida;
       this.origem = origem;
       this.data = data;
       this.latitudeInicial = latitudeInicial;
       this.latitudeFinal = latitudeFinal;
       this.longitudeInicial = longitudeInicial;
       this.destino = destino;
       this.longitudeFinal = longitudeFinal;
    }
   
    public String getIdtransporte() {
        return this.idtransporte;
    }
    
    public void setIdtransporte(String idtransporte) {
        this.idtransporte = idtransporte;
    }
    public Aparelho getAparelho() {
        return this.aparelho;
    }
    
    public void setAparelho(Aparelho aparelho) {
        this.aparelho = aparelho;
    }
    public Caixa getCaixa() {
        return this.caixa;
    }
    
    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }
    public Motorista getMotorista() {
        return this.motorista;
    }
    
    public void setMotorista(Motorista motorista) {
        this.motorista = motorista;
    }
    public String getTempFinal() {
        return this.tempFinal;
    }
    
    public void setTempFinal(String tempFinal) {
        this.tempFinal = tempFinal;
    }
    public String getTempInicial() {
        return this.tempInicial;
    }
    
    public void setTempInicial(String tempInicial) {
        this.tempInicial = tempInicial;
    }
    public Date getHoraSaida() {
        return this.horaSaida;
    }
    
    public void setHoraSaida(Date horaSaida) {
        this.horaSaida = horaSaida;
    }
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getLatitudeInicial() {
        return this.latitudeInicial;
    }
    
    public void setLatitudeInicial(String latitudeInicial) {
        this.latitudeInicial = latitudeInicial;
    }
    public String getLatitudeFinal() {
        return this.latitudeFinal;
    }
    
    public void setLatitudeFinal(String latitudeFinal) {
        this.latitudeFinal = latitudeFinal;
    }
    public String getLongitudeInicial() {
        return this.longitudeInicial;
    }
    
    public void setLongitudeInicial(String longitudeInicial) {
        this.longitudeInicial = longitudeInicial;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public String getLongitudeFinal() {
        return this.longitudeFinal;
    }
    
    public void setLongitudeFinal(String longitudeFinal) {
        this.longitudeFinal = longitudeFinal;
    }




}


