package Model;
// Generated Oct 9, 2016 7:43:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transplante generated by hbm2java
 */
public class Transplante  implements java.io.Serializable {


     private String idtransplante;
     private Receptor receptor;
     private Usuario usuario;
     private Date dataTransplante;
     private Set orgaos = new HashSet(0);

    public Transplante() {
    }

	
    public Transplante(String idtransplante, Receptor receptor, Usuario usuario) {
        this.idtransplante = idtransplante;
        this.receptor = receptor;
        this.usuario = usuario;
    }
    public Transplante(String idtransplante, Receptor receptor, Usuario usuario, Date dataTransplante, Set orgaos) {
       this.idtransplante = idtransplante;
       this.receptor = receptor;
       this.usuario = usuario;
       this.dataTransplante = dataTransplante;
       this.orgaos = orgaos;
    }
   
    public String getIdtransplante() {
        return this.idtransplante;
    }
    
    public void setIdtransplante(String idtransplante) {
        this.idtransplante = idtransplante;
    }
    public Receptor getReceptor() {
        return this.receptor;
    }
    
    public void setReceptor(Receptor receptor) {
        this.receptor = receptor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataTransplante() {
        return this.dataTransplante;
    }
    
    public void setDataTransplante(Date dataTransplante) {
        this.dataTransplante = dataTransplante;
    }
    public Set getOrgaos() {
        return this.orgaos;
    }
    
    public void setOrgaos(Set orgaos) {
        this.orgaos = orgaos;
    }




}


